export {default as Banner} from "./Banner/Banner"
export {default as WhyVaccinate} from "./WhyVaccinate/WhyVaccinate"
export {default as Symptoms} from "./Symptoms/Symptoms"
export {default as Feedback} from "./Feedback/Feedback"
export {default as Footer} from "./Footer/Footer"